### ISSUE TITLE
How to modify "internal nodes" to update the stacking space?

### ISSUE THREAD

**Issue by LugwigButMrLu** [alexfrom0815/Online-3D-BPP-PCT#10]
Thank you for your sharing, it's an incredible job! 
I‘ve read your paper and am interested in the real-world experiments. I found that the size of the new box can be defined by the class `bincreator`, but I'd love to know how you "correct the descriptor of the corresponding internal node b ∈ B with the offset position". Could you please give a specific location in the code？
Finally, I would also like to know what your LICENSE is and if I can modify it for further study and research.
Thank you whatever and best wishes for you!

**Comment by alexfrom0815** [comment]
Hi, thanks for your attention.
1. Regarding the modification of internal node, you only need to modify the space.box_vec variable in the ‘space.py’ file after the offset box position information is accessed.
2. Regarding the license, we do not use the existing license, so we reserve all rights of this project. We do not allow unauthorized commercial use of this repo, but encourage academics to use it for free.
Hope this helps you.

**Comment by LugwigButMrLu** [comment]
> Hi, thanks for your attention.
> 
> 1. Regarding the modification of internal node, you only need to modify the space.box_vec variable in the ‘space.py’ file after the offset box position information is accessed.
> 2. Regarding the license, we do not use the existing license, so we reserve all rights of this project. We do not allow unauthorized commercial use of this repo, but encourage academics to use it for free.
>    Hope this helps you.

Thanks for your kind explanation, it worked!
I'm an amateur RL & webots beginner, and I'm just doing it out of fun. It will NOT be used for any commercial purpose. 
My issue has been resolved so I will close it, SINCERE RESPECT to you again!
