### ISSUE TITLE
Is it possible to add "preview" (like bpp-k) to the code? 

### ISSUE THREAD

**Issue by Chengjlzzz** [alexfrom0815/Online-3D-BPP-PCT#11]
Dear author,
Thanks for your sharing!
I found the "BPP-K" function in your paper "Online 3D Bin Packing with Constrained Deep Reinforcement Learning" is not added to the code. Is it possible to join the preview function to the code?
Thanks for your sharing again!

**Comment by alexfrom0815** [comment]
Thanks for your attention, this is a great suggestion! But unfortunately, I have some other projects going on recently and have no energy to expand the PCT project at the moment. If you need it urgently, I suggest you refer to our previous project to implement this feature.

**Comment by Chengjlzzz** [comment]
> Thanks for your attention, this is a great suggestion! But unfortunately, I have some other projects going on recently and have no energy to expand the PCT project at the moment. If you need it urgently, I suggest you refer to our previous project to implement this feature.

Thanks for your reply, I will try it.
