### ISSUE TITLE
AssertionError: You must specify a action space

### ISSUE THREAD

**Issue by Jayleelwj** [alexfrom0815/Online-3D-BPP-PCT#16]
Dear authors:

I am trying to reproduce your experiments claimed in your ICLR paper. But I got an error "You must specify a action space",  the whole error information can be found below. Would you mind please providing some helpful information for this?

/home/liwj/gitcode/Online-3D-BPP-PCT/attention_model.py:9: DeprecationWarning: __class__ not set defining 'AttentionModelFixed' as <class 'attention_model.AttentionModelFixed'>. Was __classcell__ propagated to type.__new__?
  class AttentionModelFixed(NamedTuple):
Please input the experiment name
pct
[(1, 1, 1), (1, 1, 2), (1, 1, 3), (1, 1, 4), (1, 1, 5), (1, 2, 1), (1, 2, 2), (1, 2, 3), (1, 2, 4), (1, 2, 5), (1, 3, 1), (1, 3, 2), (1, 3, 3), (1, 3, 4), (1, 3, 5), (1, 4, 1), (1, 4, 2), (1, 4, 3), (1, 4, 4), (1, 4, 5), (1, 5, 1), (1, 5, 2), (1, 5, 3), (1, 5, 4), (1, 5, 5), (2, 1, 1), (2, 1, 2), (2, 1, 3), (2, 1, 4), (2, 1, 5), (2, 2, 1), (2, 2, 2), (2, 2, 3), (2, 2, 4), (2, 2, 5), (2, 3, 1), (2, 3, 2), (2, 3, 3), (2, 3, 4), (2, 3, 5), (2, 4, 1), (2, 4, 2), (2, 4, 3), (2, 4, 4), (2, 4, 5), (2, 5, 1), (2, 5, 2), (2, 5, 3), (2, 5, 4), (2, 5, 5), (3, 1, 1), (3, 1, 2), (3, 1, 3), (3, 1, 4), (3, 1, 5), (3, 2, 1), (3, 2, 2), (3, 2, 3), (3, 2, 4), (3, 2, 5), (3, 3, 1), (3, 3, 2), (3, 3, 3), (3, 3, 4), (3, 3, 5), (3, 4, 1), (3, 4, 2), (3, 4, 3), (3, 4, 4), (3, 4, 5), (3, 5, 1), (3, 5, 2), (3, 5, 3), (3, 5, 4), (3, 5, 5), (4, 1, 1), (4, 1, 2), (4, 1, 3), (4, 1, 4), (4, 1, 5), (4, 2, 1), (4, 2, 2), (4, 2, 3), (4, 2, 4), (4, 2, 5), (4, 3, 1), (4, 3, 2), (4, 3, 3), (4, 3, 4), (4, 3, 5), (4, 4, 1), (4, 4, 2), (4, 4, 3), (4, 4, 4), (4, 4, 5), (4, 5, 1), (4, 5, 2), (4, 5, 3), (4, 5, 4), (4, 5, 5), (5, 1, 1), (5, 1, 2), (5, 1, 3), (5, 1, 4), (5, 1, 5), (5, 2, 1), (5, 2, 2), (5, 2, 3), (5, 2, 4), (5, 2, 5), (5, 3, 1), (5, 3, 2), (5, 3, 3), (5, 3, 4), (5, 3, 5), (5, 4, 1), (5, 4, 2), (5, 4, 3), (5, 4, 4), (5, 4, 5), (5, 5, 1), (5, 5, 2), (5, 5, 3), (5, 5, 4), (5, 5, 5)]
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    main(args)
  File "main.py", line 43, in main
    envs = make_vec_envs(args, './logs/runinfo', True)
  File "/home/liwj/gitcode/Online-3D-BPP-PCT/envs.py", line 104, in make_vec_envs
    sample_right_bound=args.sample_right_bound
  File "/home/liwj/.conda/envs/pytorch-wenjie/lib/python3.7/site-packages/gym/envs/registration.py", line 601, in make
    env = PassiveEnvChecker(env)
  File "/home/liwj/.conda/envs/pytorch-wenjie/lib/python3.7/site-packages/gym/wrappers/env_checker.py", line 24, in __init__
    ), "You must specify a action space. https://www.gymlibrary.ml/content/environment_creation/"
AssertionError: You must specify a action space. https://www.gymlibrary.ml/content/environment_creation/

**Comment by Jayleelwj** [comment]
I run the common listed in README.md

```
python main.py
```

**Comment by alexfrom0815** [comment]
I have not encountered this error when using gym, maybe we are using a different gym version, the version I am currently using is gym==0.13.0

**Comment by Jayleelwj** [comment]
Thanks for your reply! The issue has been addressed by downgrading the gym package to 0.13.0. Thx.
