### ISSUE TITLE
Running on cpu

### ISSUE THREAD

**Issue by Gangstart** [alexfrom0815/Online-3D-BPP-PCT#2]
Dear author:
        Thanks for your sharing! I am really interested in your work! I'm a graduate student and new to reinforcement learning. How can I modify the code to train the model through the CPU instead of GPU?

**Comment by alexfrom0815** [comment]
> Dear author: Thanks for your sharing! I am really interested in your work! I'm a graduate student and new to reinforcement learning. How can I modify the code to train the model through the CPU instead of GPU?

Hello, thank you for your attention and the code has been modified accordingly. Add --no-cuda to the command line, you can deploy the code on the CPU.
