### ISSUE TITLE
How to get the 3D visualization?

### ISSUE THREAD

**Issue by HeegerGao** [alexfrom0815/Online-3D-BPP-PCT#22]
Hi, I am very interested in your work. I want to visualize your results like those done in the C.5 section (VISUALIZED RESULTS) of your paper. Is there any off-the-shelf code that I can use? Thanks!

**Comment by parilo** [comment]
Agree, visualisation code would be very helpful

**Comment by alexfrom0815** [comment]
Thank you for your attention. My general habit is to use the rendering tools in graphics to render them after getting the packing results, so this part of the code has not been integrated into this repo. In the future, we will add some python-based fast rendering tools, such as matplotlib, which can draw some simple visualization results in three-dimensional space.
