### ISSUE TITLE
AttributeError: 'PackingDiscrete' object has no attribute 'action_space'

### ISSUE THREAD

**Issue by TD-zane** [alexfrom0815/Online-3D-BPP-PCT#3]
Hi,

When I type "python main.py ", I get that error quickly.

Full error trace:

Traceback (most recent call last):
File "main.py", line 55, in <module>
    main(args)
  File "main.py", line 40, in main
    envs = make_vec_envs(args, './logs/runinfo', True)
  File "G:\graduate design\code\Online-3D-BPP-PCT-main\envs.py", line 108, in make_vec_envs
    spaces = [env.observation_space, env.action_space]
  File "E:\anaconda\envs\Online3D\lib\site-packages\gym\core.py", line 229, in __getattr__
    return getattr(self.env, name)
AttributeError: 'PackingDiscrete' object has no attribute 'action_space'

Thanks in advance.

Regards

**Comment by alexfrom0815** [comment]
Hello, thanks for your feedback, this project is being continuously updated, the problem you mentioned seems to have been resolved in the latest version, please try it.

**Comment by desmondddd** [comment]
I still have this problem with the latest codes.

**Comment by alexfrom0815** [comment]
> 

This is weird because the code I downloaded from this repository is directly runnable, the environment version I use is Python == 3.7.7, torch == 1.10.1, gym == 0.15.7, hope this helps you.

**Comment by TD-zane** [comment]
Thank you for your sharing. In your Online-3D-BPP-PCT project, I noticed that it is mainly for the implementation of the packing strategy for Bpp-1. I would like to consult you if I need to add the MCTS code content to the PCT project content if I want to solve the Bpp-K packing problem (mentioned in your Online-3D-BPP-DRL project).
Thanks in advance for your reply!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alexfrom0815/Online-3D-BPP-PCT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月12日(星期六) 晚上6:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alexfrom0815/Online-3D-BPP-PCT] AttributeError: 'PackingDiscrete' object has no attribute 'action_space' (Issue #3)





   
This is weird because the code I downloaded from this repository is directly runnable, the environment version I use is Python == 3.7.7, torch == 1.10.1, gym == 0.15.7, hope this helps you.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alexfrom0815** [comment]
> Thank you for your sharing. In your Online-3D-BPP-PCT project, I noticed that it is mainly for the implementation of the packing strategy for Bpp-1. I would like to consult you if I need to add the MCTS code content to the PCT project content if I want to solve the Bpp-K packing problem (mentioned in your Online-3D-BPP-DRL project). Thanks in advance for your reply!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alexfrom0815/Online-3D-BPP-PCT" ***@***.***&gt;; 发送时间:&nbsp;2022年3月12日(星期六) 晚上6:48 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [alexfrom0815/Online-3D-BPP-PCT] AttributeError: 'PackingDiscrete' object has no attribute 'action_space' (Issue #3) This is weird because the code I downloaded from this repository is directly runnable, the environment version I use is Python == 3.7.7, torch == 1.10.1, gym == 0.15.7, hope this helps you. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Hello, Online-3D-BPP-PCT focuses on the case of BPP-1, it is a general strategy module that can be used to solve problems such as multi-bin online 3D-BPP, online 3D-BPP with lookahead. Due to time reasons , I have not organized these functions into this repo for now. If you are interested, you can refer to our past projects (Online-3D-BPP-DRL) or our article (https://arxiv.org/pdf/ 2006.14978.pdf) to achieve BPP-K. Best wishes!

**Comment by alexfrom0815** [comment]
Hello, Online-3D-BPP-PCT focuses on the case of BPP-1, it is a general strategy module that can be used to solve problems such as multi-bin online 3D-BPP, online 3D-BPP with lookahead. Due to time reasons , I have not organized these functions into this repo for now. If you are interested, you can refer to our past projects (Online-3D-BPP-DRL) or our article (https://arxiv.org/pdf/ 2006.14978.pdf) to achieve BPP-K. Best wishes!

**Comment by TD-zane** [comment]
Thank you very much for your reply, thank you again for your selfless sharing, I have another question about whether this project is online or offline learning: as far as I understand, online learning is usually input one piece of data at a time (not one batch) , directly update the weights after training.While offline learning, similar to batch learning, updates the weights after a batch of training.Can we input one data for training at a time in the training of this project?


Thank you in advance for your reply, and I wish your research and study better and better!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alexfrom0815/Online-3D-BPP-PCT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月4日(星期一) 上午8:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alexfrom0815/Online-3D-BPP-PCT] AttributeError: 'PackingDiscrete' object has no attribute 'action_space' (Issue #3)





 
Hello, Online-3D-BPP-PCT focuses on the case of BPP-1, it is a general strategy module that can be used to solve problems such as multi-bin online 3D-BPP, online 3D-BPP with lookahead. Due to time reasons , I have not organized these functions into this repo for now. If you are interested, you can refer to our past projects (Online-3D-BPP-DRL) or our article (https://arxiv.org/pdf/ 2006.14978.pdf) to achieve BPP-K. Best wishes!

**Comment by llzll1031** [comment]
How long do you need to train on discrete domain？
