### ISSUE TITLE
RuntimeError: __class__ not set defining

### ISSUE THREAD

**Issue by Chengjlzzz** [alexfrom0815/Online-3D-BPP-PCT#4]
Dear author:
Thanks for your sharing! When I ran main.py, I got an error:

Traceback (most recent call last):
  File "E:/User002/Online-3D-BPP-PCT-main/main.py", line 6, in <module>
    from model import *
  File "E:\User002\Online-3D-BPP-PCT-main\model.py", line 4, in <module>
    from attention_model import AttentionModel
  File "E:\User002\Online-3D-BPP-PCT-main\attention_model.py", line 9, in <module>
    class AttentionModelFixed(NamedTuple):
RuntimeError: __class__ not set defining 'AttentionModelFixed' as <class 'attention_model.AttentionModelFixed'>. Was __classcell__ propagated to type.__new__?

Process finished with exit code 1

python3.8
pytorch1.9.0

**Comment by Xiong5Heng** [comment]
I have the same error, and my training environment is python 3.8.5 and pytorch 1.7.1.

**Comment by Xiong5Heng** [comment]
> I have the same error, and my training environment is python 3.8.5 and pytorch 1.7.1.

I find this problem may be caused due to the version of python and super() function of NamedTuple, and I change the line         return super(AttentionModelFixed, self).__getitem__(key) (https://github.com/alexfrom0815/Online-3D-BPP-PCT/blob/de50b187c32af18b850dc20c53d8b2bcce16510d/attention_model.py#L25) to return tuple.__getitem__(self, key), and luckily, it works. But I don't know if this modification will change the result of the code.

**Comment by alexfrom0815** [comment]
Sorry for the delayed reply due to tons of things, the version I'm using is: Python == 3.7.7, torch == 1.10.1, this works on my computer. Hope this helps you.

**Comment by Chengjlzzz** [comment]
> > I have the same error, and my training environment is python 3.8.5 and pytorch 1.7.1.
> 
> I find this problem may be caused due to the version of python and super() function of NamedTuple, and I change the line
> 
> https://github.com/alexfrom0815/Online-3D-BPP-PCT/blob/de50b187c32af18b850dc20c53d8b2bcce16510d/attention_model.py#L25
> 
> to
> `return tuple.__getitem__(self, key)`
> , and luckily, it works. But I don't know if this modification will change the result of the code.

Thanks, it works.

**Comment by Chengjlzzz** [comment]
> Sorry for the delayed reply due to tons of things, the version I'm using is: Python == 3.7.7, torch == 1.10.1, this works on my computer. Hope this helps you.

Thanks a lot!

**Comment by yehudaFabric** [comment]
Thanks for this thread, helped me a lot
