### ISSUE TITLE
Online learning or Offline learning

### ISSUE THREAD

**Issue by TD-zane** [alexfrom0815/Online-3D-BPP-PCT#7]
Hello,I have a question about whether this project is online or offline learning: as far as I understand, online learning is usually input one piece of data at a time (not one batch) , directly update the weights after training.While offline learning, similar to batch learning, updates the weights after a batch of training.Can we input one data for training at a time in the training of this project?

Thank you in advance for your reply, and best wishes to you!

**Comment by alexfrom0815** [comment]
By your definition, this project is for offline learning because the data for each training is randomly generated. You can modify binCreator.py so that the agent encounters the same problem every time for online learning needs.

**Comment by TD-zane** [comment]
Thank you very much for your reply.Best wishes to you!



---Original---
From: ***@***.***&gt;
Date: Sat, Apr 9, 2022 08:52 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alexfrom0815/Online-3D-BPP-PCT] Online learning or Offlinelearning (Issue #7)




 
By your definition, this project is for offline learning because the data for each training is randomly generated. You can modify binCreator.py so that the agent encounters the same problem every time for online learning needs.
