### ISSUE TITLE
The network structure

### ISSUE THREAD

**Issue by TD-zane** [alexfrom0815/Online-3D-BPP-PCT#9]
Thank you very much for your selfless sharing. 
I noticed that you did not show the details of the network structure in the paper, but you showed your deep reinforcement learning network structure based on the ACKTR algorithm in the Online-3D-BPP-DRL(https://github.com/alexfrom0815/Online-3D-BPP-DRL) paper. Is the network structure of deep reinforcement learning the same in this PCT paper? Or do you have a suggestion for a quick way to see the structure of the PCT network?
Thanks in advance for your reply. Best wishes for you!

**Comment by alexfrom0815** [comment]
Hi, thanks for your attention. In the work of PCT, we use the graph attention network to extract the features of the problem. This part of the code is mainly integrated in 'attention_model.py' and 'graph_encoder.py'. Unlike PCT, our previous work mainly uses CNN to extract question features.

**Comment by TD-zane** [comment]
Hello, thank you very much for your reply. I noticed the difference and connection between the graph neural network in the PCT article and the CNN part in the DRL article.&nbsp;
Regarding the deep reinforcement learning network structure in the PCT article, I noticed that you still use the acktr algorithm and network structure in the DRL article.&nbsp;
Therefore,I would like to consult you about if you have tried other deep learning algorithms such as TRPO, SAC, ACER, etc. methods? Or are there obvious reasons these algorithms are inferior to the acktr algorithm and we don't need to try?



---Original---
From: ***@***.***&gt;
Date: Thu, Apr 28, 2022 13:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alexfrom0815/Online-3D-BPP-PCT] The network structure (Issue #9)




 
Hi, thanks for your attention. In the work of PCT, we use the graph attention network to extract the features of the problem. This part of the code is mainly integrated in 'attention_model.py' and 'graph_encoder.py'. Unlike PCT, our previous work mainly uses CNN to extract question features.

**Comment by JSA-458** [comment]
> Hi, thanks for your attention. In the work of PCT, we use the graph attention network to extract the features of the problem. This part of the code is mainly integrated in 'attention_model.py' and 'graph_encoder.py'. Unlike PCT, our previous work mainly uses CNN to extract question features.

Dear author:
Thanks for your sharing!
I would like to consult you about the network structure of  DRL.Which part of the project is this part of the code mainly integrated into?Is the DRL structure same as your previous work in 2021?
Thanks for your sharing again! Best wishes for you!

**Comment by alexfrom0815** [comment]
> In the work of PCT, we use the graph attention network to extract the features of the problem. This part of the code is mainly integrated in 'attention_model.py' and 'graph_encoder.py'. Unlike PCT, our previous work mainly uses CNN to extract question features.

In this work, we use the graph attention network (GAT) to extract the features of the problem. This part of the code is mainly integrated in 'attention_model.py' and 'graph_encoder.py'. Different from PCT, our previous work in 2021 mainly uses CNN to extract question features.

**Comment by alexfrom0815** [comment]
> Hello, thank you very much for your reply. I noticed the difference and connection between the graph neural network in the PCT article and the CNN part in the DRL article.&nbsp; Regarding the deep reinforcement learning network structure in the PCT article, I noticed that you still use the acktr algorithm and network structure in the DRL article.&nbsp; Therefore,I would like to consult you about if you have tried other deep learning algorithms such as TRPO, SAC, ACER, etc. methods? Or are there obvious reasons these algorithms are inferior to the acktr algorithm and we don't need to try?
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Apr 28, 2022 13:08 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [alexfrom0815/Online-3D-BPP-PCT] The network structure (Issue #9) Hi, thanks for your attention. In the work of PCT, we use the graph attention network to extract the features of the problem. This part of the code is mainly integrated in 'attention_model.py' and 'graph_encoder.py'. Unlike PCT, our previous work mainly uses CNN to extract question features. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Our experiment results show that ACKTR works the best among mainstream RL algs. But we also encourage you to try other SOTA RL algs, maybe you can get different and even better results.

**Comment by TD-zane** [comment]
> > Hello, thank you very much for your reply. I noticed the difference and connection between the graph neural network in the PCT article and the CNN part in the DRL article.  Regarding the deep reinforcement learning network structure in the PCT article, I noticed that you still use the acktr algorithm and network structure in the DRL article.  Therefore,I would like to consult you about if you have tried other deep learning algorithms such as TRPO, SAC, ACER, etc. methods? Or are there obvious reasons these algorithms are inferior to the acktr algorithm and we don't need to try?
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Thu, Apr 28, 2022 13:08 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [alexfrom0815/Online-3D-BPP-PCT] The network structure (Issue #9) Hi, thanks for your attention. In the work of PCT, we use the graph attention network to extract the features of the problem. This part of the code is mainly integrated in 'attention_model.py' and 'graph_encoder.py'. Unlike PCT, our previous work mainly uses CNN to extract question features. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> Our experiment results show that ACKTR works the best among mainstream RL algs. But we also encourage you to try other SOTA RL algs, maybe you can get different and even better results.

Thanks for your reply.Best wishes to you!
